import { User, Vehicle, DamageType, VehicleStatus } from './types';

export const CURRENT_USER: User | null = null;

export const MOCK_USERS: User[] = [];

export const MOCK_VEHICLES: Vehicle[] = [];

export const TRANSLATIONS: any = {
  'English (US)': {
    dashboard: "Dashboard",
    auctions: "Auctions",
    sell: "Sell Vehicle",
    settings: "Settings",
    language: "Language",
    logout: "Logout",
    welcomeBack: "Welcome back",
    joinAutoBid: "Join AutoBid",
    enterCredentials: "Enter your credentials to continue",
    startJourney: "Start your journey today",
    username: "Username",
    email: "Email address",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordsNoMatch: "Passwords do not match",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    createAccount: "Create Account",
    orContinue: "Or continue with",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    raiseTicket: "Raise Ticket",
    viewTickets: "View Tickets",
    contactSupport: "Contact Support",
    credentialsData: "Credentials & Data",
    changePassword: "Change Password",
    loginDevices: "Login Devices",
    downloadData: "Download Data",
    loginSection: "Login",
    addAccount: "Add Account",
    switchAccount: "Switch Account",
    logOut: "Log Out",
    blockedUsers: "Blocked Users",
    languages: "Languages",
    verifyAccount: "Verify Account",
    aiAssistant: "AI Assistant",
    backToSearch: "Back to Search",
    vehicleSpecs: "Vehicle Specs",
    vin: "VIN",
    odometer: "Odometer",
    primaryDamage: "Primary Damage",
    secondaryDamage: "Secondary Damage",
    engine: "Engine",
    topSpeed: "Top Speed",
    mpg: "MPG",
    keys: "Keys",
    sellerDesc: "Seller Description",
    aiInsight: "AI Insight",
    currentBid: "Current Bid",
    buyNow: "Buy Now",
    setMaxBid: "Set Max Bid",
    placeBid: "Place Bid",
    addToWatchlist: "Add to Watchlist",
    saleStatus: "Sale Status",
    saleDate: "Sale Date",
    timeLeft: "Time Left",
    liveAuctions: "Live Auctions",
    profile: "Profile",
    searchPlaceholder: "Search vehicles...",
    allAuctions: "All Auctions",
    upcoming: "Upcoming",
    footerAboutText: "AutoBid is the premier destination for vehicle auctions.",
    todaysAuctions: "Today's Auctions",
    joinAuction: "Join Auction",
    auctionCalendar: "Auction Calendar",
    footerServices: "Services",
    transportation: "Transportation",
    conditionReports: "Condition Reports",
    brokerServices: "Broker Services",
    footerSupport: "Support",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    locations: "Locations",
    footerRights: "© 2026 AutoBid. All rights reserved."
  },
  en: {
    dashboard: "Dashboard",
    auctions: "Auctions",
    sell: "Sell Vehicle",
    settings: "Settings",
    language: "Language",
    logout: "Logout",
    welcomeBack: "Welcome back",
    joinAutoBid: "Join AutoBid",
    enterCredentials: "Enter your credentials to continue",
    startJourney: "Start your journey today",
    username: "Username",
    email: "Email address",
    password: "Password",
    confirmPassword: "Confirm Password",
    passwordsNoMatch: "Passwords do not match",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    createAccount: "Create Account",
    orContinue: "Or continue with",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    raiseTicket: "Raise Ticket",
    viewTickets: "View Tickets",
    contactSupport: "Contact Support",
    credentialsData: "Credentials & Data",
    changePassword: "Change Password",
    loginDevices: "Login Devices",
    downloadData: "Download Data",
    loginSection: "Login",
    addAccount: "Add Account",
    switchAccount: "Switch Account",
    logOut: "Log Out",
    blockedUsers: "Blocked Users",
    languages: "Languages",
    verifyAccount: "Verify Account",
    aiAssistant: "AI Assistant",
    backToSearch: "Back to Search",
    vehicleSpecs: "Vehicle Specs",
    vin: "VIN",
    odometer: "Odometer",
    primaryDamage: "Primary Damage",
    secondaryDamage: "Secondary Damage",
    engine: "Engine",
    topSpeed: "Top Speed",
    mpg: "MPG",
    keys: "Keys",
    sellerDesc: "Seller Description",
    aiInsight: "AI Insight",
    currentBid: "Current Bid",
    buyNow: "Buy Now",
    setMaxBid: "Set Max Bid",
    placeBid: "Place Bid",
    addToWatchlist: "Add to Watchlist",
    saleStatus: "Sale Status",
    saleDate: "Sale Date",
    timeLeft: "Time Left",
    liveAuctions: "Live Auctions",
    profile: "Profile",
    searchPlaceholder: "Search vehicles...",
    allAuctions: "All Auctions",
    upcoming: "Upcoming",
    footerAboutText: "AutoBid is the premier destination for vehicle auctions.",
    todaysAuctions: "Today's Auctions",
    joinAuction: "Join Auction",
    auctionCalendar: "Auction Calendar",
    footerServices: "Services",
    transportation: "Transportation",
    conditionReports: "Condition Reports",
    brokerServices: "Broker Services",
    footerSupport: "Support",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    locations: "Locations",
    footerRights: "© 2026 AutoBid. All rights reserved."
  }
};

export const CAR_BRANDS = [
  "Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Bugatti", 
  "Buick", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Dodge", "Ferrari", 
  "Fiat", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "Infiniti", "Jaguar", 
  "Jeep", "Kia", "Koenigsegg", "Lamborghini", "Land Rover", "Lexus", "Lincoln", 
  "Lotus", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "Mini", "Mitsubishi", 
  "Nissan", "Pagani", "Peugeot", "Porsche", "Ram", "Renault", "Rolls-Royce", 
  "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo", "Rivian", "Lucid",
  "Polestar", "Fisker", "BYD", "Nio", "Xpeng"
].sort();

export const COMMON_CAR_MODELS: Record<string, string[]> = {
  Toyota: ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma", "Tundra", "Prius", "4Runner", "Sienna", "Crown", "Fortuner", "Innova Crysta"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "HR-V", "Odyssey", "Passport", "City", "Amaze", "Elevate"],
  Ford: ["F-150", "Mustang", "Explorer", "Escape", "Bronco", "Edge", "Ranger", "Expedition", "Maverick"],
  Chevrolet: ["Silverado 1500", "Equinox", "Malibu", "Tahoe", "Traverse", "Colorado", "Suburban", "Camaro", "Corvette"],
  BMW: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "M3", "M4", "M5", "i4", "iX"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLS", "CLA", "GLA", "A-Class", "G-Class"],
  Audi: ["A3", "A4", "A5", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Palisade", "Venue", "Creta", "Ioniq 5", "Verna"],
  Kia: ["Forte", "K5", "Sportage", "Sorento", "Telluride", "Soul", "EV6", "Seltos", "Sonet"],
  Nissan: ["Altima", "Sentra", "Rogue", "Pathfinder", "Murano", "Frontier", "Titan", "Z", "Kicks"],
  Volkswagen: ["Jetta", "Passat", "Golf GTI", "Tiguan", "Atlas", "Taos", "ID.4", "Virtus", "Polo"],
  Suzuki: ["Swift", "Baleno", "Dzire", "Brezza", "Ertiga", "Grand Vitara", "Jimny", "Alto", "WagonR"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Subaru: ["Outback", "Forester", "Crosstrek", "Impreza", "WRX", "Ascent", "BRZ"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Cayman"],
  Lexus: ["ES", "RX", "NX", "IS", "GX", "LX"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Gladiator"],
  Mazda: ["Mazda3", "Mazda6", "CX-5", "CX-30", "CX-50", "MX-5 Miata"]
};
